---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
  pep8:
    enabled: true
    checks:
      E731:
        enabled: false
  radon:
    enabled: true
    exclude_fingerprints:
    - bfff0bc9cc3192cec5f6a67ac86e4848
    - e013761bcd2d4f84881e4bcacb62b061
    - 24ddcb6d660b0e80660c6eeb6c1e5d8d
    - f7bf748fba4025d70b1ccf41982538e1
    - 2e177f566eebd902996a42ccc955f20e
    - 2e177f566eebd902996a42ccc955f20e
    - 2e177f566eebd902996a42ccc955f20e
    - 6e81a92c93c510b66793ab96b59d285f
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- "scratchpad.py"
- "data/migrations/0001_initial.py"
